#!/bin/sh

get_mac_binary() {
	local path="$1"
	local offset="$2"

	if ! [ -e "$path" ]; then
		echo "get_mac_binary: file $path not found!" >&2
		return
	fi

	hexdump -v -n 6 -s $offset -e '5/1 "%02x:" 1/1 "%02x"' $path 2>/dev/null
}

mtd_get_mac_binary() {
	local mtdname="$1"
	local offset="$2"
	local part

	#part=$(find_mtd_part "$mtdname") 修改
	get_mac_binary "$part" "$offset"
}

[ -f init_root ] || {
	touch init_root
	macaddr=$(mtd_get_mac_binary mfginfo 0x2a)
	echo root:"${macaddr}" | chpasswd
}
